import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import './protocols.css'
import { api, type State } from './api'

type Page = 'home' | 'activities' | 'recovery' | 'monthly' | 'profile' | 'testing' | 'team' | 'notifications'
const emptySetup = { workspaceName: '', displayName: '', email: '', username: '', pin: '' }

function App() {
  const [state, setState] = useState<State | null>(null)
  const [setupRequired, setSetupRequired] = useState<boolean | null>(null)
  const [error, setError] = useState('')
  const [page, setPage] = useState<Page>('home')
  const refresh = async () => { try { setState(await api.bootstrap()); setError('') } catch (e) { setState(null); setError(e instanceof Error ? e.message : 'Unable to load the workspace') } }
  useEffect(() => { api.setupStatus().then(x => { setSetupRequired(x.setupRequired); if (!x.setupRequired) refresh() }).catch(e => setError(e.message)) }, [])
  const inviteToken = new URLSearchParams(window.location.search).get('invite')
  const resetToken = new URLSearchParams(window.location.search).get('reset')
  const usernameToken = new URLSearchParams(window.location.search).get('username')
  if (setupRequired === null) return <main className="auth-shell"><p>Loading RUN|CAL…</p></main>
  if (inviteToken) return <AcceptInvite token={inviteToken} onDone={() => { window.history.replaceState({}, '', '/'); refresh() }} />
  if (resetToken) return <ResetPin token={resetToken} />
  if (usernameToken) return <UsernameLookup token={usernameToken} />
  if (setupRequired) return <Setup onDone={() => { setSetupRequired(false); refresh() }} />
  if (!state) return <Login onDone={refresh} error={error} />
  return <Workspace state={state} page={page} setPage={setPage} refresh={refresh} />
}

function AcceptInvite({ token, onDone }: { token: string; onDone: () => void }) {
  const [displayName,setDisplayName]=useState(''),[username,setUsername]=useState(''),[pin,setPin]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api.acceptInvite({token,displayName,username,pin});onDone()}catch(x){setError(x instanceof Error?x.message:'Unable to accept invitation')}finally{setBusy(false)}}
  return <main className="auth-shell"><section className="auth-card"><Brand /><p className="eyebrow">TEAM INVITATION</p><h1>Set up your account</h1><p className="muted">Choose a permanent Username and a 6-digit PIN.</p><form className="form-stack" onSubmit={submit}><Field label="Display name" value={displayName} onChange={setDisplayName}/><Field label="Username (4–8 letters, numbers, - or _)" value={username} onChange={setUsername}/><Field label="6-digit PIN" type="password" inputMode="numeric" value={pin} onChange={v=>setPin(v.replace(/\D/g,'').slice(0,6))}/>{error&&<p className="error">{error}</p>}<button disabled={busy} className="primary">{busy?'Creating…':'Accept invitation'}</button></form></section></main>
}

function Setup({ onDone }: { onDone: () => void }) {
  const [form, setForm] = useState(emptySetup), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); try { await api.setup(form); onDone() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create workspace') } finally { setBusy(false) } }
  return <main className="auth-shell"><section className="auth-card"><Brand /><p className="eyebrow">FIRST-TIME SETUP</p><h1>Create your first team</h1><p className="muted">This account becomes the Team Admin. You can invite Coaches and Athletes afterwards.</p><form onSubmit={submit} className="form-stack"><Field label="Team name" value={form.workspaceName} onChange={v => setForm({ ...form, workspaceName: v })} /><Field label="Your display name" value={form.displayName} onChange={v => setForm({ ...form, displayName: v })} /><Field label="Email" type="email" value={form.email} onChange={v => setForm({ ...form, email: v })} /><Field label="Username (4–8 letters, numbers, - or _)" value={form.username} onChange={v => setForm({ ...form, username: v })} /><Field label="6-digit PIN" type="password" inputMode="numeric" value={form.pin} onChange={v => setForm({ ...form, pin: v.replace(/\D/g, '').slice(0, 6) })} />{error && <p className="error">{error}</p>}<button disabled={busy} className="primary">{busy ? 'Creating…' : 'Create team'}</button></form></section></main>
}

function Login({ onDone, error: initialError }: { onDone: () => void; error: string }) {
  const [username, setUsername] = useState(''), [pin, setPin] = useState(''), [email,setEmail]=useState(''), [mode,setMode]=useState<'login'|'username'|'reset'>('login'), [error, setError] = useState(initialError), [notice,setNotice]=useState(''), [busy, setBusy] = useState(false)
  const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); try { if(mode==='login') { await api.login(username, pin); onDone() } else { const result=mode==='username'?await api.requestUsername(email):await api.requestPinReset(email); setNotice(result.message) } } catch (err) { setError(err instanceof Error ? err.message : 'Unable to continue') } finally { setBusy(false) } }
  return <main className="auth-shell"><section className="auth-card"><Brand /><h1>{mode==='login'?'Welcome back':mode==='username'?'Find your Username':'Reset your PIN'}</h1><p className="muted">{mode==='login'?'Sign in with your Username and 6-digit PIN.': 'Enter your registered email. A one-hour verification link will be sent when team email is connected.'}</p><form onSubmit={submit} className="form-stack">{mode==='login'?<><Field label="Username" value={username} onChange={setUsername}/><Field label="PIN" type="password" inputMode="numeric" value={pin} onChange={v=>setPin(v.replace(/\D/g,'').slice(0,6))}/></>:<Field label="Registered email" type="email" value={email} onChange={setEmail}/>} {error&&<p className="error">{error}</p>}{notice&&<p className="notice">{notice}</p>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Send verification link'}</button></form><div className="auth-links"><button onClick={()=>{setMode('login');setError('');setNotice('')}}>Sign in</button><button onClick={()=>{setMode('username');setError('');setNotice('')}}>Check Username</button><button onClick={()=>{setMode('reset');setError('');setNotice('')}}>Reset PIN</button></div></section></main>
}

function ResetPin({token}:{token:string}){const[pin,setPin]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await api.confirmPinReset(token,pin);setMessage('PIN reset complete. Please sign in.')}catch(x){setError(x instanceof Error?x.message:'Unable to reset PIN')}};return <main className="auth-shell"><section className="auth-card"><Brand/><h1>Choose a new PIN</h1><form className="form-stack" onSubmit={submit}><Field label="New 6-digit PIN" type="password" inputMode="numeric" value={pin} onChange={v=>setPin(v.replace(/\D/g,'').slice(0,6))}/>{error&&<p className="error">{error}</p>}{message&&<p className="notice">{message}</p>}<button className="primary">Reset PIN</button></form></section></main>}
function UsernameLookup({token}:{token:string}){const[username,setUsername]=useState(''),[error,setError]=useState('');useEffect(()=>{api.verifyUsername(token).then(x=>setUsername(x.username)).catch(x=>setError(x.message))},[token]);return <main className="auth-shell"><section className="auth-card"><Brand/><h1>Your Username</h1>{error?<p className="error">{error}</p>:username?<p className="username-result">{username}</p>:<p className="muted">Verifying link…</p>}</section></main>}

function Workspace({ state, page, setPage, refresh }: { state: State; page: Page; setPage: (p: Page) => void; refresh: () => void }) {
  const roles = state.workspace.roles; const athlete = roles.includes('athlete'); const admin = roles.includes('team_admin'); const unread = state.notifications.filter(n => !n.readAt).length
  const nav: Array<[Page, string]> = [['home', 'Overview'], ['activities', 'Activities'], ['recovery', 'Daily recovery'], ['monthly', 'Monthly log'], ['profile', 'My profile'], ...(athlete ? [['testing', 'Testing protocols'] as [Page, string]] : []), ...(admin ? [['team', 'Team admin'] as [Page, string]] : []), ['notifications', `Notifications${unread ? ` (${unread})` : ''}`]]
  const signOut = async () => { await api.logout(); window.location.reload() }
  return <div className="app-shell"><aside><Brand /><div className="identity"><b>{state.user.displayName}</b><span>{roles.map(r => r.replace('_', ' ')).join(' · ')}</span><small>{state.workspace.workspaceName}</small></div><nav>{nav.map(([key, label]) => <button className={key === page ? 'active' : ''} onClick={() => setPage(key)} key={key}>{label}</button>)}</nav><button className="signout" onClick={signOut}>Sign out</button></aside><main className="workspace"><header><span>{state.workspace.workspaceName}</span><span className="role-badge">{roles.join(' · ')}</span></header><div className="content">{page === 'home' && <Home state={state} setPage={setPage} />}{page === 'activities' && <Activities state={state} refresh={refresh} athlete={athlete} />}{page === 'recovery' && <Recovery state={state} refresh={refresh} athlete={athlete} />}{page === 'monthly' && <Monthly state={state} refresh={refresh} athlete={athlete} />}{page === 'profile' && <Profile state={state} refresh={refresh} athlete={athlete} />}{page === 'testing' && athlete && <TestingProtocols />}{page === 'team' && admin && <Team state={state} refresh={refresh} />}{page === 'notifications' && <Notifications state={state} refresh={refresh} />}</div></main></div>
}

function Home({ state, setPage }: { state: State; setPage: (p: Page) => void }) {
  const recovery = state.recovery ? Math.round((state.recovery.sleep + state.recovery.energy + state.recovery.soreness + state.recovery.stress + state.recovery.mood) / 5 * 20) : null
  return <><Intro eyebrow="RUNNING WORKSPACE" title={`Hello, ${state.user.displayName.split(' ')[0]}`} text="Your data stays with this host. Start with the thing that needs your attention." /><div className="grid three"><Summary label="Recovery today" value={recovery === null ? 'Not logged' : `${recovery}/100`} note={recovery === null ? 'Complete your five scores.' : 'Average of five check-in areas.'} action={() => setPage('recovery')} /><Summary label="Activities" value={String(state.activities.filter(a => !a.deletedAt).length)} note="FIT activities available to review." action={() => setPage('activities')} /><Summary label="Unread" value={String(state.notifications.filter(n => !n.readAt).length)} note="Your in-app notifications." action={() => setPage('notifications')} /></div><section className="panel"><h2>Latest activities</h2>{state.activities.slice(0, 5).map(a => <div className="row" key={a.id}><span><b>{a.title}</b><small>{a.activityDate} · {a.originalName}</small></span><span className={a.deletedAt ? 'status deleted' : 'status'}>{a.deletedAt ? 'Deleted' : 'Available'}</span></div>)}{!state.activities.length && <Empty text="No FIT activities yet. Import your first running file from Activities." />}</section></>
}

function Activities({ state, refresh, athlete }: { state: State; refresh: () => void; athlete: boolean }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const upload = async (files: FileList | null) => { if (!files?.length) return; if (files.length > 10) return setMessage('You can import a maximum of 10 FIT files at once.'); setBusy(true); try { for (const file of Array.from(files)) await api.fit(file); setMessage('FIT files validated and imported. Available activity metrics have been saved.'); await refresh() } catch (e) { setMessage(e instanceof Error ? e.message : 'Import failed') } finally { setBusy(false) } }
  return <><Intro eyebrow="FIT IMPORT" title="Activities" text="Import running FIT files from your device. Only values available in a file are shown." /><section className="panel"><label className="upload"><input type="file" accept=".fit" multiple disabled={!athlete || busy} onChange={e => upload(e.target.files)} /><b>{busy ? 'Importing…' : 'Choose up to 10 .FIT files'}</b><span>Files are private to your workspace.</span></label>{message && <p className="notice">{message}</p>}</section><section className="panel"><h2>Your activity history</h2>{state.activities.map(a => <div className="row" key={a.id}><span><b>{a.title}</b><small>{a.activityDate} · {Math.round(a.byteSize / 1024)} KB</small></span><span className={a.deletedAt ? 'status deleted' : 'status'}>{a.deletedAt ? 'In 30-day bin' : 'Imported'}</span></div>)}{!state.activities.length && <Empty text="No imported FIT files." />}</section></>
}

function Recovery({ state, refresh, athlete }: { state: State; refresh: () => void; athlete: boolean }) {
  const initial = state.recovery || { sleep: 3, energy: 3, soreness: 3, stress: 3, mood: 3, note: '' }; const [data, setData] = useState(initial), [message, setMessage] = useState('')
  const save = async (e: FormEvent) => { e.preventDefault(); try { await api.recovery(data); setMessage('Daily recovery saved.'); await refresh() } catch (x) { setMessage(x instanceof Error ? x.message : 'Unable to save') } }
  return <><Intro eyebrow="08:00 DAILY CHECK-IN" title="Daily recovery" text="Score each area 1–5. The overall score is an average, not a medical assessment." /><form onSubmit={save} className="panel form-stack">{(['sleep', 'energy', 'soreness', 'stress', 'mood'] as const).map(k => <label className="score-field" key={k}><span>{k}</span><input type="range" min="1" max="5" value={data[k]} disabled={!athlete} onChange={e => setData({ ...data, [k]: Number(e.target.value) })} /><b>{data[k]} / 5</b></label>)}<label>Optional note<textarea value={data.note} disabled={!athlete} onChange={e => setData({ ...data, note: e.target.value })} placeholder="Anything your coach should know?" /></label>{message && <p className="notice">{message}</p>}<button className="primary" disabled={!athlete}>Save daily recovery</button></form></>
}

function Monthly({ state, refresh, athlete }: { state: State; refresh: () => void; athlete: boolean }) {
  const [weightKg, setWeight] = useState(''), [cpWatts, setCp] = useState(''), [wkg, setWkg] = useState(''), [comment, setComment] = useState(''), [message, setMessage] = useState(''); const usesStryd = !!state.profile?.usesStryd
  const submit = async (e: FormEvent) => { e.preventDefault(); try { await api.monthly({ month: new Date().toISOString().slice(0, 7), weightKg: Number(weightKg), cpWatts: usesStryd ? Number(cpWatts) : null, comment }); setMessage('Monthly log saved and locked.'); await refresh() } catch (x) { setMessage(x instanceof Error ? x.message : 'Unable to save') } }
  return <><Intro eyebrow="MONTHLY · 1ST OF THE MONTH" title="Monthly log" text="Record your weight and a note for your coach. Entries cannot be edited after saving." /><form onSubmit={submit} className="panel form-stack"><Field label="Weight (kg)" type="number" value={weightKg} onChange={setWeight} disabled={!athlete} />{usesStryd && <div className="two"><Field label="CP (watts)" type="number" value={cpWatts} onChange={setCp} disabled={!athlete} /><Field label="W/kg" type="number" value={wkg} onChange={setWkg} disabled={!athlete} /></div>}<label>Comment for coach<textarea value={comment} disabled={!athlete} onChange={e => setComment(e.target.value)} /></label>{message && <p className="notice">{message}</p>}<button className="primary" disabled={!athlete}>Save monthly log</button></form><section className="panel"><h2>History</h2>{state.monthly.map(m => <div className="row" key={m.id}><span><b>{m.month} · {m.weightKg} kg{m.cpWatts ? ` · ${m.cpWatts} W · ${m.wkg} W/kg` : ''}</b><small>{m.comment || 'No comment'}</small>{m.coachReply && <small className="reply">Coach: {m.coachReply}</small>}</span><span className="status">Locked</span></div>)}{!state.monthly.length && <Empty text="Your first log is due on the first of the month." />}</section></>
}

function Profile({ state, refresh, athlete }: { state: State; refresh: () => void; athlete: boolean }) {
  const p = state.profile; const [form, setForm] = useState({ emergencyName:p?.emergencyName || '', emergencyRelation:p?.emergencyRelation || '', emergencyPhone:p?.emergencyPhone || '', sportGoal:p?.sportGoal || '', experienceYears:String(p?.experienceYears ?? ''), experienceNote:p?.experienceNote || '', usesStryd:!!p?.usesStryd }); const [message,setMessage]=useState('')
  const save = async (e: FormEvent) => { e.preventDefault(); try { await api.profile({ ...form, experienceYears:Number(form.experienceYears) }); setMessage('Profile saved.'); await refresh() } catch(x) { setMessage(x instanceof Error ? x.message : 'Unable to save') } }
  return <><Intro eyebrow="YOUR PROFILE" title="Athlete profile" text="Emergency contact, goals and experience are required. Your email is managed by Team Admin." /><form className="panel form-stack" onSubmit={save}><div className="two"><Field label="Emergency contact name" value={form.emergencyName} disabled={!athlete} onChange={v=>setForm({...form,emergencyName:v})}/><Field label="Relationship" value={form.emergencyRelation} disabled={!athlete} onChange={v=>setForm({...form,emergencyRelation:v})}/></div><Field label="Emergency contact phone" value={form.emergencyPhone} disabled={!athlete} onChange={v=>setForm({...form,emergencyPhone:v})}/><label>Sport goal<textarea value={form.sportGoal} disabled={!athlete} onChange={e=>setForm({...form,sportGoal:e.target.value})}/></label><div className="two"><Field label="Years of sport experience" type="number" value={form.experienceYears} disabled={!athlete} onChange={v=>setForm({...form,experienceYears:v})}/><label className="checkbox"><input type="checkbox" checked={form.usesStryd} disabled={!athlete} onChange={e=>setForm({...form,usesStryd:e.target.checked})}/> I use Stryd</label></div><label>Experience details<textarea value={form.experienceNote} disabled={!athlete} onChange={e=>setForm({...form,experienceNote:e.target.value})}/></label>{message&&<p className="notice">{message}</p>}<button className="primary" disabled={!athlete}>Save profile</button></form></>
}

type TestKind = 'critical' | 'ramp' | 'thirty' | 'fivek' | 'lthr5k' | 'lthr30' | 'hydration'
type TestResult = { label: string; value: string; detail: string; zones?: Array<{ name: string; value: string }> }

const paceZones = [['Recovery', .65, .78], ['Endurance', .78, .88], ['Tempo', .88, .94], ['Threshold', .95, 1.03], ['Anaerobic / VO2max', 1.04, 1.4]] as const
const hrZones = [['Recovery', 0, .85], ['Endurance', .85, .89], ['Tempo', .9, .94], ['Threshold', .95, 1.02], ['Anaerobic / VO2max', 1.03, 1.4]] as const
const numberValue = (form: Record<string, string>, key: string) => Number(form[key])
const paceText = (speed: number) => { const seconds = 1000 / speed; return `${Math.floor(seconds / 60)}:${String(Math.round(seconds % 60)).padStart(2, '0')} /km` }

function TestingProtocols() {
  const [kind, setKind] = useState<TestKind>('critical'), [form, setForm] = useState<Record<string, string>>({}), [result, setResult] = useState<TestResult | null>(null), [error, setError] = useState(''), [history, setHistory] = useState<TestResult[]>([])
  const update = (key: string, value: string) => { setForm({ ...form, [key]: value }); setResult(null); setError('') }
  const fields: Record<TestKind, Array<[string, string, string]>> = {
    critical: [['Distance 1 (m)', 'd1', 'number'], ['Time 1 (seconds)', 't1', 'number'], ['Distance 2 (m)', 'd2', 'number'], ['Time 2 (seconds)', 't2', 'number']],
    ramp: [['Last completed speed (km/h)', 'speed', 'number'], ['Incomplete stage (seconds)', 'incomplete', 'number']],
    thirty: [['Distance (m)', 'distance', 'number']], fivek: [['5K time (seconds)', 'time', 'number']],
    lthr5k: [['Average 5K heart rate (BPM)', 'hr', 'number']], lthr30: [['Average HR, minutes 10–30 (BPM)', 'hr', 'number']],
    hydration: [['Duration (minutes)', 'duration', 'number'], ['Pre-exercise weight (kg)', 'pre', 'number'], ['Post-exercise weight (kg)', 'post', 'number'], ['Fluid consumed (ml, optional)', 'fluid', 'number'], ['Urine produced (ml, optional)', 'urine', 'number'], ['Expected race duration (hours, optional)', 'race', 'number'], ['Bottle capacity (ml, optional)', 'bottle', 'number']]
  }
  const calculate = (event: FormEvent) => { event.preventDefault(); const optional = kind === 'hydration' ? ['fluid', 'urine', 'race', 'bottle'] : []; const invalid = Object.entries(form).some(([key, value]) => !optional.includes(key) && (value === '' || !Number.isFinite(Number(value)) || Number(value) < 0)); if (invalid) return setError('Complete the required fields with valid non-negative numbers.'); if (kind === 'hydration' && (numberValue(form, 'duration') <= 0 || numberValue(form, 'pre') <= 0)) return setError('Duration and pre-exercise weight must be greater than zero.'); if (['thirty', 'fivek', 'lthr5k', 'lthr30'].includes(kind) && Object.values(form).some(value => Number(value) <= 0)) return setError('The test input must be greater than zero.')
    let next: TestResult
    if (kind === 'critical') { const t1 = numberValue(form, 't1'), t2 = numberValue(form, 't2'); if (t1 === t2 || t1 <= 0 || t2 <= 0) return setError('Effort times must be positive and different.'); const speed = ((numberValue(form, 'd2') / t2) * t2 - (numberValue(form, 'd1') / t1) * t1) / (t2 - t1) * .94; next = paceResult('Critical Pace', speed) }
    else if (kind === 'ramp') next = paceResult('RAMP LTP', ((numberValue(form, 'speed') + numberValue(form, 'incomplete') / 180) / 3.6) * .824)
    else if (kind === 'thirty') next = paceResult('30-Minute Run LTP', numberValue(form, 'distance') / 1800)
    else if (kind === 'fivek') next = paceResult('5K Run LTP', (5000 / numberValue(form, 'time')) * .9)
    else if (kind === 'lthr5k') next = hrResult('5K LTHR', numberValue(form, 'hr') / 1.04)
    else if (kind === 'lthr30') next = hrResult('30-Minute LTHR', numberValue(form, 'hr'))
    else { const duration = numberValue(form, 'duration'); const loss = numberValue(form, 'pre') - numberValue(form, 'post'); const sweat = loss + numberValue(form, 'fluid') / 1000 - numberValue(form, 'urine') / 1000; const rate = sweat / (duration / 60) * 1000; const raceTotal = rate * .75 * numberValue(form, 'race'); const bottles = numberValue(form, 'bottle') ? Math.ceil(raceTotal / numberValue(form, 'bottle')) : 0; next = { label: 'Sweat-rate test', value: `${Math.round(rate)} ml/hour`, detail: `75% starting fluid target: ${Math.round(rate * .75)} ml/hour · Race total: ${Math.round(raceTotal)} ml · Bottles: ${bottles}` }; if (numberValue(form, 'post') > numberValue(form, 'pre') || Math.abs(loss) / numberValue(form, 'pre') > .03 || numberValue(form, 'fluid') / 1000 > sweat || duration < 30) next.detail += ' Review the test warnings before using these starting points.' }
    setResult(next); setError('')
  }
  const save = () => { if (result) setHistory([result, ...history]) }
  const paceResult = (label: string, speed: number): TestResult => ({ label, value: paceText(speed), detail: 'LTP speed is used to preview pace zones.', zones: paceZones.map(([name, lo, hi]) => ({ name, value: `${paceText(speed * lo)}–${paceText(speed * hi)}` })) })
  const hrResult = (label: string, hr: number): TestResult => ({ label, value: `${Math.round(hr)} BPM`, detail: 'LTHR is used to preview heart-rate zones.', zones: hrZones.map(([name, lo, hi]) => ({ name, value: `${Math.round(hr * lo)}–${Math.round(hr * hi)} BPM` })) })
  return <><Intro eyebrow="ATHLETE PROFILE · TESTING" title="Testing protocols" text="Calculate an isolated test result. Nothing changes in Training Load, Recovery, activities or zones until a separate confirmed profile update exists." /><section className="panel protocol-panel"><label>Protocol<select value={kind} onChange={e => { setKind(e.target.value as TestKind); setForm({}); setResult(null); setError('') }}><option value="critical">LTP · Critical Pace</option><option value="ramp">LTP · RAMP</option><option value="thirty">LTP · 30-Minute Run</option><option value="fivek">LTP · 5K Run</option><option value="lthr5k">LTHR · 5K</option><option value="lthr30">LTHR · 30-Minute Run</option><option value="hydration">Hydration · Sweat rate</option></select></label><form className="form-stack" onSubmit={calculate}>{fields[kind].map(([label, key, type]) => <Field key={key} label={label} type={type} value={form[key] || ''} onChange={value => update(key, value)} />)}{error && <p className="error">{error}</p>}<button className="primary">Calculate preview</button></form></section>{result && <section className="panel protocol-result"><p className="eyebrow">CALCULATED PREVIEW</p><h2>{result.label}</h2><strong>{result.value}</strong><p className="muted">{result.detail}</p>{result.zones && <div className="zone-list">{result.zones.map(zone => <div className="zone" key={zone.name}><span>{zone.name}</span><b>{zone.value}</b></div>)}</div>}<button className="secondary" onClick={save}>Save test to session history</button></section>}{history.length > 0 && <section className="panel"><h2>Session history</h2>{history.map((item, index) => <div className="row" key={`${item.label}-${index}`}><span><b>{item.label}</b><small>{item.value}</small></span><span className="status">Isolated</span></div>)}</section>}</>
}

function Team({ state, refresh }: { state: State; refresh: () => void }) { const [email,setEmail]=useState(''), [role,setRole]=useState('athlete'), [message,setMessage]=useState(''),[transferUser,setTransferUser]=useState(''),[pin,setPin]=useState(''); const send=async(e:FormEvent)=>{e.preventDefault();try{const result=await api.invite(email,[role]);setEmail('');setMessage(`Invite created. It expires in ${result.expiresInMinutes} minutes. ${result.delivery}`);await refresh()}catch(x){setMessage(x instanceof Error?x.message:'Unable to invite')}};const transfer=async(e:FormEvent)=>{e.preventDefault();try{const result=await api.startAdminTransfer(transferUser,pin);setMessage(`Transfer requested. The recipient must accept within 60 minutes. Token: ${result.transferToken}`);setPin('')}catch(x){setMessage(x instanceof Error?x.message:'Unable to request transfer')}}; return <><Intro eyebrow="TEAM MANAGEMENT" title="Invite a member" text="Athlete is the default role. Invitations expire after one hour and do not use a capacity seat until accepted."/><form className="panel inline-form" onSubmit={send}><Field label="Email" type="email" value={email} onChange={setEmail}/><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="athlete">Athlete</option><option value="coach">Coach</option></select></label><button className="primary">Create invite</button></form>{message&&<p className="notice">{message}</p>}<section className="panel"><h2>Team members</h2>{state.members.map(m=><div className="row" key={m.id}><span><b>{m.displayName}{m.isTeamAdmin?' · Team Admin':''}</b><small>{m.email} · {m.roles.join(' · ')}</small></span></div>)}</section><form className="panel form-stack" onSubmit={transfer}><h2>Transfer Team Admin</h2><p className="muted">The recipient must accept the transfer. Your team email connection is revoked when transfer completes.</p><label>New Team Admin<select value={transferUser} onChange={e=>setTransferUser(e.target.value)}><option value="">Choose a member</option>{state.members.filter(m=>!m.isTeamAdmin).map(m=><option value={m.id} key={m.id}>{m.displayName}</option>)}</select></label><Field label="Confirm your 6-digit PIN" type="password" inputMode="numeric" value={pin} onChange={v=>setPin(v.replace(/\D/g,'').slice(0,6))}/><button className="primary">Request transfer</button></form></> }

function Notifications({ state, refresh }: { state: State; refresh: () => void }) { const mark = async(id:string)=>{await api.markRead(id);await refresh()}; const accept = async(id:string)=>{await api.acceptAdminTransfer(id);await refresh()}; return <><Intro eyebrow="IN-APP ONLY" title="Notifications" text="Unread items remain here until you mark them as read."/><section className="panel">{state.notifications.map(n=>{const transferId=n.href.startsWith('/team?transfer=')?n.href.split('=').at(-1):''; return <div className="row" key={n.id}><span><b>{n.title}</b><small>{n.body}</small></span>{transferId?<button className="primary" onClick={()=>accept(transferId!)}>Accept transfer</button>:n.readAt?<span className="status">Read</span>:<button className="secondary" onClick={()=>mark(n.id)}>Mark read</button>}</div>})}{!state.notifications.length&&<Empty text="You are all caught up."/>}</section></> }

function Brand(){return <div className="brand"><span>↗</span>RUN<span>|</span>CAL</div>}; function Intro({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="intro"><small>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div>}; function Field({label,value,onChange,type='text',disabled,inputMode}:{label:string;value:string;onChange:(v:string)=>void;type?:string;disabled?:boolean;inputMode?:React.HTMLAttributes<HTMLInputElement>['inputMode']}){return <label>{label}<input type={type} value={value} disabled={disabled} inputMode={inputMode} onChange={e=>onChange(e.target.value)}/></label>}; function Summary({label,value,note,action}:{label:string;value:string;note:string;action:()=>void}){return <button className="summary" onClick={action}><small>{label}</small><b>{value}</b><span>{note}</span></button>}; function Empty({text}:{text:string}){return <p className="empty">{text}</p>}
export default App
